runtime: nodejs14
instance_class: F2

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico))$
    static_files: build/\1
    upload: build/.*\.(json|ico)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always